# Generated by Django 3.2.6 on 2021-08-31 02:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('serial_number', models.CharField(max_length=30)),
                ('device_category', models.CharField(choices=[('EXAM_CAM', 'Exam Cameras'), ('CAMERA', 'Camera'), ('MOBILE', 'Mobile'), ('STETH', 'Stethoscope'), ('DENTAL', 'Dental'), ('MULTIPURPOSE', 'Other Device'), ('TOOL', 'Tool'), ('SUPPLIES', 'Supplies'), ('PRODUCTION_AUDIO', 'Production: Audio'), ('PRODUCTION_VIDEO', 'Production: Video'), ('OTHER', 'Other/Misc.')], max_length=30)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.location')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.item_status')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='items',
            field=models.ManyToManyField(to='tracker.Item'),
        ),
    ]
