# Generated by Django 3.2.6 on 2021-08-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210830_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item_status',
            options={'verbose_name_plural': 'item status'},
        ),
    ]
