# Generated by Django 3.2.6 on 2021-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_item_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
